services:
  mongodb:
    image: mongo:6.0
    container_name: music-player-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./my-backend-project
      dockerfile: Dockerfile
    container_name: music-player-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_URI: ${DB_URI}
      CLOUD_NAME: ${CLOUD_NAME}
      CLOUD_API_KEY: ${CLOUD_API_KEY}
      CLOUD_API_SECRET: ${CLOUD_API_SECRET}
    depends_on:
      - mongodb

volumes:
  mongo-data:
